### PR TITLE
[ENH]: Add a Dockerfile for a base resen image

### PR DESCRIPTION
**Pull request by asreimer**
It takes quite awhile for all of the apt-get stuff to run when building the resen-core Dockerfile. For development and testing purposes, this makes is take much longer when building from scratch.

In preparation for adding CI, I've created a resen-base Dockerfile that is intended to provide an image from which resen-cores can be based.

Thoughts? This PR is only intended to introduce a resen-base Dockerfile. A subsequent PR can modify the resen-core Dockerfile to use a resen-base image in dockerhub later.

### CODE REVIEW

**Comment by pmreyes2** [comment]
This would really help the development of resen-core images. It has all the apt-get installs that I are needed. I would just include `screen`, not essential but useful for persistent terminal sessions.

**Comment by asreimer** [comment]
@pmreyes2 What does screen offer that keeping a jupyterlab terminal window open doesn't?

**Comment by pmreyes2** [comment]
@asreimer, the use of `screen` is just a user preference. I still use it  exactly because it is independent of `jupyter`. Its like some people like to use `vim`, others `nano`, and others `emacs` (all of them included in this base image). I repeat, its not essential, and since there is sudo, if the user wants to use it, then `sudo apt-get install screen`.

**Review by pmreyes2 — APPROVED** [review]

**Comment by asreimer** [comment]
I completely understand that this is a user preference and that this isn't essential.

I don't actually see the utility in including `vim`, `emacs`, and `nano` being installed since the builtin text editor in `jupyter` has keybinding for vim and emacs: https://jupyterlab.readthedocs.io/en/stable/user/file_editor.html

`screen` is only ~1MB to install. It would be trivial to add.

Remember, the intention of this base image is to act as a base image from which people can develop resen-cores. If it's just user preference, then it probably shouldn't really be in the base image.

**Comment by pmreyes2** [comment]
Here is another thought:
I know jupyter lab has nice browsing capabilities, and has editors. But it doesn't have things like "go back to the previous folder" `$ cd -`.

**Comment by pmreyes2** [comment]
@asreimer I think this should be merged.

**Pull request merged**
