### PR TITLE
Adding nodejs and extension manager that allows %matplotlib widget and other third-party extensions

### PR DESCRIPTION
**Pull request by pmreyes2**
This pull request adds `nodejs` to` resen-core` (extra ~600MB) which allows `extension manager` to be installed. `extension manager` allows third-party extensions to be installed in `jupyter`. The pull request also adds the `jupyter-matplotlib` (per enhancement discussion: [resen-core#42](https://github.com/EarthCubeInGeo/resen-core/issues/42)) extension which offers zoom and scroll capabilities to 2D and 3D `matplotlib` plots. Interesting third-party extensions that users will be able to install on their own:

- [@jupyter-matplotlib](https://github.com/matplotlib/ipympl)  (already in the pull request per enhancement discussion: [resen-core#42](https://github.com/EarthCubeInGeo/resen-core/issues/42))
- [hdfviewer](https://pypi.org/project/hdfviewer)
- [jupyterlab-spreadsheet](https://github.com/quigleyj97/jupyterlab-spreadsheet#readme) (supports XLS, XLSX, and CSV files)
- [@jupyterlab/google-drive](https://www.npmjs.com/package/@jupyterlab/google-drive) This would allow to access google drive storage.
- [k3d](https://github.com/K3D-tools/K3D-jupyter#readme) (3D visualization library)
...

### CODE REVIEW

**Comment by ljlamarche** [comment]
Also note that this PR includes all the other geospace packages we wanted to include in the next release (#42).

**Comment by valentic** [comment]
This also would solve the HDF5 viewer problem - this extension looks 
nice and exactly what we've talked about needing:

https://www.npmjs.com/package/@jupyterlab/hdf5

Todd

**Comment by pmreyes2** [comment]
Unfortunately when trying to install [https://www.npmjs.com/package/@jupyterlab/hdf5](https://www.npmjs.com/package/@jupyterlab/hdf5)
the following error message appears:
```
$ jupyter labextension install @jupyterlab/hdf5
An error occured.
ValueError: The extension "@jupyterlab/hdf5" does not yet support the current version of JupyterLab.


Conflicting Dependencies:
JupyterLab              Extension      Package
>=2.1.2 <2.2.0          >=1.2.0 <2.0.0 @jupyterlab/application
>=2.1.1 <2.2.0          >=1.2.0 <2.0.0 @jupyterlab/apputils
>=4.1.0 <4.2.0          >=3.2.0 <4.0.0 @jupyterlab/coreutils
>=2.1.2 <2.2.0          >=1.2.0 <2.0.0 @jupyterlab/docmanager
>=2.1.2 <2.2.0          >=1.2.0 <2.0.0 @jupyterlab/filebrowser
>=2.1.2 <2.2.0          >=1.2.0 <2.0.0 @jupyterlab/notebook
>=5.1.0 <5.2.0          >=4.2.0 <5.0.0 @jupyterlab/services
See the log file for details:  /tmp/jupyterlab-debug-ahp38o1b.log
```
I was going to add it to the list but there are some things to sort out first with the versions. The HDF5 viewer that worked right out of the pip install was [https://pypi.org/project/hdfviewer](https://pypi.org/project/hdfviewer). A screenshot below shows its `matplotlib` interactive view of its contents. Its not perfect, for single numeric value, the value doesn't show, only its attributes.

Screen Shot 2020-05-20 at 5 34 21 PM

**Comment by ljlamarche** [comment]
Going ahead and merging this to prepare release candidate.

**Pull request merged**
