### PR TITLE
Tutorials v2020.2.0

### PR DESCRIPTION
**Pull request by ljlamarche**
Includes updated tutorials for new packages.  This should be merged AFTER #61.

Outstanding issue:  Will [sciunit2](https://sciunit.run/) be included in resen-core v2020.2.0?  If not, the sciunit section should be removed from the `GeospacePackagesInResen.ipynb` tutorial.  If so, that section of the tutorial should be expanded to include an example of the [sciunit API](https://sciunit.run/docs/).

### CODE REVIEW

**Comment by ljlamarche** [comment]
Tutorials finalized.  Sciunit2 has been added, but the API example is not clear, so it's been left out for now.

**Comment by ljlamarche** [comment]
Ok, I pushed the latest update and confirmed this PR does include the updating the citationhelper file.  Should be ready for review/merging now!

**Review by asreimer — COMMENTED** [review]
Looks good overall. I encountered a couple problems:
bokeh
but I can't seem to reproduce this problem now. Weird. Let's just remember this in case we see it again later.

And this problem with sunpy:
sunpy

**Comment by ljlamarche** [comment]
Is the Bokeh issue one you encountered a while ago?  I know we did have to add the [jupyter_bokeh extension](https://docs.bokeh.org/en/latest/docs/user_guide/jupyter.html) (77bf1a0ee4cce50a06697790fe9f960d9deb6c63).

As far as the sunpy issue, I've seen that before as well.  It appears to be some kind of non-fatal internal sunpy error, so I'm not quite sure what to do about it.  Maybe just show a different example function?

**Comment by asreimer** [comment]
Offline discussions found that if we upgrade the sunpy package, the error will go away: https://github.com/sunpy/sunpy/issues/4483

Merging this and adding a commit to develop to update sunpy.

**Pull request merged**
