### PR TITLE
Adding mangopy to py27 and py36 environments

### PR DESCRIPTION
**Pull request by pmreyes2**
Created a helper script that is called from Dockerfile.

### CODE REVIEW

**Comment by asreimer** [comment]
We could do this without helper scripts, via:

    pip install git+git://github.com/astib/MANGO.git@b25cba78e58197394809cb8323656a1d636c3e3d

See: https://stackoverflow.com/questions/13685920/install-specific-git-commit-with-pip

Since `mangopy` is a purely python package, I don't think we need to add a helper script for it. `pyglow` will probably be different, but we could probably do this same kind of one-liner installs with pip for nearly all of the `setup_*.sh` helper scripts actually. For example, cartopy could be installed with the one-liner:

    LDFLAGS="-shared"  pip install --no-use-pep517 git+git://github.com/SciTools/cartopy.git@v0.17.0

What do you think?

**Comment by pmreyes2** [comment]
I agree. I'll change this it for mangopy.

**Comment by pmreyes2** [comment]
Done in the last commit.
BTW,` pip install git+git:// ...` didn't work. What worked was `pip install git+https:// ...`
In this commit I have also updated the test_py36_imports.py and test_py27_imports.py tests to include importing mangopy

**Comment by asreimer** [comment]
`git+git` doesn't work? It works perfectly on my Fedora 29 system with pip version 19.1.1:
image
image
Strange. When I get to testing this I'll dig.

**Comment by pmreyes2** [comment]
Well, the current git version in resen-core for environments base, py27, and py36 is 19.0.3. That might be the problem. The output I got running from resen-core running container is:

```
(py36) jovyan@7e2a09022c4b:~/work$ pip install git+git://github.com/astib/MANGO.git@b25cba78e58197394809cb8323656a1d636c3e3d
Collecting git+git://github.com/astib/MANGO.git@b25cba78e58197394809cb8323656a1d636c3e3d
  Cloning git://github.com/astib/MANGO.git (to revision b25cba78e58197394809cb8323656a1d636c3e3d) to /tmp/pip-req-build-j0jcklf4

fatal: unable to connect to github.com:
github.com[0: 192.30.255.112]: errno=Connection refused

Command "git clone -q git://github.com/astib/MANGO.git /tmp/pip-req-build-j0jcklf4" failed with error code 128 in None
You are using pip version 19.0.3, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by asreimer** [comment]
Does attaching to the container, upgrading to 19.1.1 and then running the pip install command fix the problem? If not, might just be a network problem on your end.
I'm nearly done the PR for the new create_bucket workflow, then I can switch gears and test this.

**Comment by pmreyes2** [comment]
Looking forward for the new create_bucket workflow.
BTW, Inside resen-core container I updated to pip-19.1.1 and still no joy:
```
(py36) jovyan@7e2a09022c4b:~/work$ pip install git+git://github.com/astib/MANGO.git@b25cba78e58197394809cb8323656a1d636c3e3d
Collecting git+git://github.com/astib/MANGO.git@b25cba78e58197394809cb8323656a1d636c3e3d
  Cloning git://github.com/astib/MANGO.git (to revision b25cba78e58197394809cb8323656a1d636c3e3d) to /tmp/pip-req-build-opm3pcb_
  Running command git clone -q git://github.com/astib/MANGO.git /tmp/pip-req-build-opm3pcb_
  fatal: unable to connect to github.com:
  github.com[0: 192.30.255.112]: errno=Connection refused

ERROR: Command "git clone -q git://github.com/astib/MANGO.git /tmp/pip-req-build-opm3pcb_" failed with error code 128 in None
```

**Comment by asreimer** [comment]
Sorry @pmreyes2, looks like this is entirely a problem on your end:

    docker run -it --name testing ac8e2819e502 bash
    jovyan@88379b528039:~/work$ conda activate py36
    jovyan@88379b528039:~/work$ pip install git+git://github.com/astib/MANGO.git@b25cba78e58197394809cb8323656a1d636c3e3d
    Collecting git+git://github.com/astib/MANGO.git@b25cba78e58197394809cb8323656a1d636c3e3d
      Cloning git://github.com/astib/MANGO.git (to revision b25cba78e58197394809cb8323656a1d636c3e3d) to /tmp/pip-req-build-g682v2b6
    Requirement already satisfied: numpy>=1.16 in /home/jovyan/envs/py36/lib/python3.6/site-packages (from mangopy==0.1) (1.16.3)
    Requirement already satisfied: h5py>=2.9 in /home/jovyan/envs/py36/lib/python3.6/site-packages (from mangopy==0.1) (2.9.0)
    Requirement already satisfied: matplotlib>=2.2.4 in /home/jovyan/envs/py36/lib/python3.6/site-packages (from mangopy==0.1) (2.2.4)
    Requirement already satisfied: cartopy>=0.17 in /home/jovyan/envs/py36/lib/python3.6/site-packages (from mangopy==0.1) (0.17.0)
    Requirement already satisfied: scipy>=1.2 in /home/jovyan/envs/py36/lib/python3.6/site-packages (from mangopy==0.1) (1.2.1)
    Collecting future>=0.16 (from mangopy==0.1)
      Downloading https://files.pythonhosted.org/packages/90/52/e20466b85000a181e1e144fd8305caf2cf475e2f9674e797b222f8105f5f/future-0.17.1.tar.gz (829kB)
        100% |████████████████████████████████| 829kB 6.8MB/s 
    Requirement already satisfied: six in /home/jovyan/envs/py36/lib/python3.6/site-packages (from h5py>=2.9->mangopy==0.1) (1.12.0)
    Requirement already satisfied: kiwisolver>=1.0.1 in /home/jovyan/envs/py36/lib/python3.6/site-packages (from matplotlib>=2.2.4->mangopy==0.1) (1.1.0)
    Requirement already satisfied: cycler>=0.10 in /home/jovyan/envs/py36/lib/python3.6/site-packages (from matplotlib>=2.2.4->mangopy==0.1) (0.10.0)
    Requirement already satisfied: pytz in /home/jovyan/envs/py36/lib/python3.6/site-packages (from matplotlib>=2.2.4->mangopy==0.1) (2018.9)
    Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /home/jovyan/envs/py36/lib/python3.6/site-packages (from matplotlib>=2.2.4->mangopy==0.1) (2.4.0)
    Requirement already satisfied: python-dateutil>=2.1 in /home/jovyan/envs/py36/lib/python3.6/site-packages (from matplotlib>=2.2.4->mangopy==0.1) (2.8.0)
    Requirement already satisfied: shapely>=1.5.6 in /home/jovyan/envs/py36/lib/python3.6/site-packages (from cartopy>=0.17->mangopy==0.1) (1.6.4.post2)
    Requirement already satisfied: setuptools>=0.7.2 in /home/jovyan/envs/py36/lib/python3.6/site-packages (from cartopy>=0.17->mangopy==0.1) (41.0.1)
    Requirement already satisfied: pyshp>=1.1.4 in /home/jovyan/envs/py36/lib/python3.6/site-packages (from cartopy>=0.17->mangopy==0.1) (2.1.0)
    Building wheels for collected packages: mangopy, future
      Building wheel for mangopy (setup.py) ... done
      Stored in directory: /tmp/pip-ephem-wheel-cache-9yup0fhi/wheels/bb/35/f9/82cdb8908801d94eed2f7b30be77eb480284bd039879235ab3
      Building wheel for future (setup.py) ... done
      Stored in directory: /home/jovyan/.cache/pip/wheels/0c/61/d2/d6b7317325828fbb39ee6ad559dbe4664d0896da4721bf379e
    Successfully built mangopy future
    Installing collected packages: future, mangopy
    Successfully installed future-0.17.1 mangopy-0.1
    You are using pip version 19.0.3, however version 19.1.1 is available.
    You should consider upgrading via the 'pip install --upgrade pip' command.

I can successfully install with the `git+git` syntax inside the 2019.1.0rc1 resen-core.

**Comment by pmreyes2** [comment]
`git+git` syntax works when I am connected to the SRI vpn! Are you connected to a vpn?
It is some network issue. If `git+https` works in more configurations, then I think we should use it instead of `git+git`, or we would have to tell the users... have your network in a certain way.

**Comment by asreimer** [comment]
No. I don't even have access to the SRI vpn on linux. Can you use the git command when you aren't on the SRI vpn?

I think the issue is that the /etc/resolv.conf in your container is currently pointing to the SRI DNS. If you remove the container, or start up a new one while not on the VPN, what happens?

If this is a network problem on your machine, simply choosing the thing that works for you isn't going to guarantee that it always will work for others. The actual solution, will be to figure out why this isn't working and how to make it work again so that if this happens to a user we know how to fix it.

**Comment by pmreyes2** [comment]
I was not using the vpn of SRI when I started the container. I started it as you did:
`docker run -it --name testing ac8e2819e502 bash`
and still does not connect to git://
There is a workaround that I found in threads that show the same issue. e.g. [Fatal: Unable to connect to github.com #6285](https://github.com/npm/npm/issues/6285#issuecomment-56640354)
setting --global url with:
` git config --global url.https://github.com/.insteadOf git://github.com/`
which I think is essentially changing git:// to https:// 
https:// seems to be less restrictive. I wonder if there s benefit of using git:// instead of https:// ?.
Well have a good night... I am out.

**Comment by asreimer** [comment]
That still doesn't explain why it's happening on your system and not mine. Sure, we can use https:// instead of git://, but that doesn't help us if a user encounters this problem in the future.

The workaround you linked to says that the port that git uses was restricted for them, so something to do with a firewall blocking the port. 

Does `telnet github.com 9418` work from your mac? What about just running the pip command on your mac?

**Comment by pmreyes2** [comment]
Is the network at my place that has for some reason git://  port blocked, and apparently is the case for some other users too. I'll check later if its my router or my internet provider. Even the train internet has the git:// port open. I was able to access `git://` in my morning commute.

**Pull request merged**
